"""Bay horse: new deliberate letter drawing against independent horse volumes."""
from pathlib import Path
import json
S=Path(__file__).resolve().parent
def entry(text,offset):
 rows=text.strip('\n').splitlines();w=max(map(len,rows));return dict(pixels=[r.ljust(w,'.') for r in rows],offset=offset)
M=dict(identity='horse-draft-v1-drawing-02',species='adult bay horse with small forehead blaze',palette={'K':'#374138','N':'#242f2d','B':'#a86836','H':'#c78949','W':'#e6dec4','R':'#815333','S':'#5e5139','F':'#56634f','E':'#101e1c','Q':'#747667'},stylization=['Long raised neck and downward muzzle are own horse masters, with pointed ears and a fixed black mane.','Bay upper planes, broad warm flank and restrained belly shadow; fixed small ivory forehead blaze hides in rear view.','Four independently projected leg links include the pastern and solid hoof; no cloven toes.','Five-link dark hair tail is a tapered ribbon with hand-placed edge accents, not a translated still.','Compound neck/head and complete coat templates remain fixed through walking, with integer pixels and no resampling.'])
M['bodies']={
'left':entry('''
..................KKKKK
...KKKKKKKKKKKKKKKHHHHHK
..KHHHHHHHHHHHHHHHHHHHHHK
.KHHHHHHHHHHHHHHHHHHHHHHHK
KHHHHHHHHHHHHHHHHHHHHHHHHBK
KHHHHHHHHHHHHHHHHHHHHHHBBBK
KBBBBBBBBBBBBBBBBBBBBBBBBBK
KBBBBBBBBBBBBBBBBBBBBBBBBBK
KBBBBBBBBBBBBBBBBBBBBBBBBRK
.KBBBBBBBBBBBBBBBBBBBBRRRK
..KBBBBBBBBBBBBBBBBBRRRRK
...KRRRRRRRRRRRRRRRRRRK
....KSSSSSSSSSSSSSSSSK
.....KKKKKKKKKKKKKKKK
''',[-13,-8]),
'right':{'mirror':'left','offset':[-13,-8]},
'down':entry('''
....KKKKK
..KKHHHHHKK
.KHHHHHHHHHK
KHHHHHHHHHHHK
KHHHHHHHHHHBK
KHHHHHHHHHBBK
KHHHHHHHHHBBK
KHHHHHHHHHBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBRK
KBBBBBBBBBRRK
KBBBBBBBBRRRK
.KBBBBBBRRRK
.KBBBBBBRRRK
.KBBBBBRRRRK
..KBBBBRRRK
..KBBRRRRK
...KSSSSK
....KKKK
''',[-6,-12]),
'up':entry('''
....KKKKK
..KKHHHHHKK
.KHHHHHHHHHK
KHHHHHHHHHHHK
KHHHHHHHHHHBK
KHHHHHHHHHBBK
KHHHHHHHHHBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBBK
KBBBBBBBBBBRK
KBBBBBBBBBRRK
KBBBBBBBBRRRK
.KBBBBBBRRRK
.KBBBBBBRRRK
.KBBBBBRRRRK
..KBBBRRRRK
...KSSSSSK
....KKKKK
''',[-6,-9])}
M['heads']={
'left':entry('''
........K
........BK
.......KHBK
.......KHNKK
.....KKHHHNNK
....KHHHHBBNNK
...KHHHEBBBBNNK
..KHHWBBBBBBBNNK
.KHBWBBBBBBBBBNNK
KBBBWBBBBBBBBBBNNK
KBBBBBRKKRBBBBBBNNK
KNBBBRK..KBBBBBBBNK
.KNNNK....KBBBBBBNK
..KKK......KBBBBBBK
............BBBBBB
.............BBBBB
..............BBBB
...............BB
''',[-7,-7]),
'right':{'mirror':'left','offset':[-12,-7]},
'down':entry('''
.K...K
.BK.KB
.HBKHB
KHHHHHK
KHHHHHK
KHHWHHK
KBHWHBK
KENWNEK
KBNWNBK
.KNNNK
.KBWBK
.KBWBK
.KBBBK
.KNNNK
..KKK
''',[-3,-6]),
'up':entry('''
.K...K
.BK.KB
.HBKHB
KHHHHHK
KHHNHHK
KBHNHBK
.KBNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
.KBNNBK
..BBBB
''',[-3,-4])}
M['hooves']={
'near':entry('''
.KK
KQQK
KNNK
''',[-2,-1]),
'far':entry('''
KKK
BNK
''',[-1,-1]),
'rear':entry('''
KKK
BNK
NNK
''',[-1,-1])}
(S/'masters.json').write_text(json.dumps(M,indent=2)+'\n',encoding='utf8');print(M['identity'])
