"""Suffolk ewe: deliberately drawn letter masters, not quantized guide renders."""
from pathlib import Path
import json
S=Path(__file__).resolve().parent
def entry(text,offset):
 rows=text.strip('\n').splitlines();w=max(map(len,rows));return dict(pixels=[r.ljust(w,'.') for r in rows],offset=offset)
M=dict(identity='sheep-draft-v1-drawing-02',species='adult hornless Suffolk ewe',palette={'K':'#394239','N':'#222d2c','B':'#48534c','S':'#a5ae96','W':'#d9ddbf','H':'#efe7cc','F':'#7c8c75','E':'#111d1d','Q':'#64716a'},stylization=['Scalloped fleece silhouette and three broad cream planes follow the independent wool clumps; no checkerboard wool texture.','Separate fixed black face and rear poll masters; rigid walking templates retain all head and fleece pixels.','Black three-link legs terminate in tiny paired hooves, with near/far ground depths retained.','Ear blades follow independently projected rigid base/tip positions; pixel width is deliberately simplified at native scale.','The short wool tail is a fixed two-pixel tuft, not a cow tail.'])
M['bodies']={
'left':entry('''
.....KK..KKK
...KKHHKKHHHKK
..KHHHHHHHHHHHK
.KHHHHHHHHHHHHHWK
KHHHHHHHHHHHHHWWWK
KHWWWWWWWWWWWWWWWK
KWWWWWWWWWWWWWWWK
.KWWWWWWWWWWWWWSK
.KWWWWWWWWWWWSSSK
..KSSWWWWWWSSSSK
...KSSSSSSSSSSK
....KK..KKKK.K
''',[-8,-6]),
'right':{'mirror':'left','offset':[-8,-6]},
'down':entry('''
...KKK
..KHHHKK
.KHHHHHHK
KHHHHHHHWK
KHHHHHHWWK
KHHHHHWWWK
KWWWWWWWWK
KWWWWWWWWK
KWWWWWWWWK
KWWWWWWWSK
.KWWWWWSSK
.KWWWWSSK
..KSSSSK
...KKKK
''',[-5,-8]),
'up':entry('''
...KKKK
..KHHHHK
.KHHHHHHK
KHHHHHHHWK
KHHHHHHWWK
KHHHHHWWWK
KWWWWWWWWK
KWWWWWWWWK
KWWWWWWWSK
KWWWWWWSSK
.KWWWWSSK
.KWWWSSSK
..KSSSSK
...KKKK
''',[-5,-7])}
M['heads']={
'left':entry('''
....KKKK
...KBBBNK
..KBNNNNK
.KNENNNNK
KNNNNNNK
KNBBBKK
.KNNK
..KK
''',[-5,-3]),
'right':{'mirror':'left','offset':[-3,-3]},
'down':entry('''
.KKKK
KBBBBK
KBNNBK
KNENEK
KNNNNK
.KNNK
.KBBK
..KK
''',[-3,-3]),
'up':entry('''
.KKKK
KBBBBK
KBNNBK
KNNNNK
.KNNK
..KK
''',[-3,-3])}
M['hooves']={
'near':entry('''
KK
NN
EN
''',[-1,-1]),
'far':entry('''
KK
BN
''',[-1,-1]),
'rear':entry('''
KK
NN
''',[-1,-1])}
(S/'masters.json').write_text(json.dumps(M,indent=2)+'\n',encoding='utf8')
print(M['identity'])
