"""Deliberate letter rows authored against independent doe guide volumes.
No rendered palette conversion, borrowed animal silhouette or resampling.
"""
import json
from pathlib import Path
S=Path(__file__).resolve().parent
def rows(text):
 a=text.strip('\n').splitlines();w=max(map(len,a));return [r.ljust(w,'.') for r in a]
def entry(text,offset):return dict(pixels=rows(text),offset=offset)
M=dict(identity='deer-draft-v1-drawing-03',species='adult white-tailed doe',palette={'K':'#574031','S':'#806044','B':'#ad8050','H':'#cfa16b','L':'#dfc69b','C':'#efe2c2','E':'#28241f','P':'#423b32'},stylization=['Warm summer coat with broad upper-surface light and a restrained underside shadow.','White throat/muzzle and tail underside, no antlers on this adult doe.','Full head and ear clusters remain rigid throughout walking.','Front ears deliberately extend one pixel beyond the torso, following the independent ear hulls.','One-pixel cannon bones, two-pixel cloven hooves; near and far ground depths come from independent bpy projection.'])
M['bodies']={
'left':entry('''
...KK......KKKKK
..KHBK...KHHHHHHKK
..KHBKKKKHHHBBBBBHK
..KHBBHHHHBBBBBBBBHK
..KLBHBBBBBBBBBBBBBK
..KCLBBBBBBBBBBBBBSK
...KCLBBBBBBBBBBBSSK
....KCLSSSSSSSSSSSK
.....KCCLLLLLLLSSK
......KKKKKKKKKKK
''',[-10,-5]),
'right':{},
'down':entry('''
...KKK
..KHHHK
.KHHHBBK
KHHHHBBBK
KHHBBBBBK
KHBBBBBSK
KHBBBBBSK
KHBBBBBSK
KHBBBBBSK
KBBBBBSSK
.KBBBSSK
.KBSSSSK
..KSSSK
...KKK
''',[-4,-8]),
'up':entry('''
...KKK
..KHHHK
..KHBK
..KHBK
..KHBK
.KHHBBK
KHHHHBBK
KHHHBBBSK
KHHBBBBBK
KHHBBBBBK
KHBBBBBSK
KHBBBBBSK
KHBBBBBSK
KHBBBBSSK
KBBBBBSSK
.KBBSSSK
..KSSSK
...KKK
''',[-4,-13])}
M['bodies']['right']={'mirror':'left','offset':[-9,-5]}
M['heads']={
'left':entry('''
........K
.......KHK
.......KCK
.......KCK
.......KCK.K
.......KBKKSK
......KHHHBK
.....KHLBBBBK
...KKHCELBBSK
.KKBBBBBBSSK
EKCLBBSSSSK
.KCCSSKKKK
..KKKK
''',[-7,-8]),
'right':{'mirror':'left','offset':[-6,-8]},
'down':entry('''
.K.......K.
KHK.....KHK
KBCK...KCBK
.KBBK.KBBK.
..KHHHHHK..
...KHHHK...
..KLEBELK..
...KBBBK...
...KLCLK...
....KEK....
....KCK....
.....K.....
''',[-5,-6]),
'up':entry('''
.K.....K
KHK...KHK
KBBK.KBBK
.KBK.KBK
..KHHHK
..KHBBSK
..KBBBSK
...KSSK
....KK
''',[-4,-5])}
M['hooves']={'near':entry('''
PP
EP
''',[-1,0]),'far':entry('''
SS
PP
''',[-1,0]),'rear':entry('''
SP
PP
''',[-1,0])}
M['tail']={'contourWidth':3,'whiteWidth':2,'tipWidth':1}
(S/'masters.json').write_text(json.dumps(M,indent=2)+'\n',encoding='utf8')
print('DEER_MASTERS_WRITTEN',M['identity'])
