"""Holstein-specific hand-authored palette-letter masters from bpy guides."""
from pathlib import Path
import json
S=Path(__file__).resolve().parent
def entry(text,offset):
 rows=text.strip('\n').splitlines();w=max(map(len,rows));return dict(pixels=[r.ljust(w,'.') for r in rows],offset=offset)
M=dict(identity='cow-draft-v1-drawing-03',species='adult polled Holstein cow',palette={'K':'#303a37','N':'#26302e','B':'#46534d','S':'#929e91','W':'#dbdecb','H':'#f1ead2','R':'#ce9c92','Q':'#a87773','F':'#677364','E':'#161f1e'},stylization=['Broad ivory upper planes with stable irregular black coat clusters, restrained gray underside.','Large pink muzzle, lateral ears and split hoof tips; rear has a different head/heel master.','Every marking is a complete static template throughout walking; skull/torso share one integer rounding phase.','Legs follow three independently projected rigid links, with upper roots covered by the torso.','Thin tail ribbon has a dark tuft and follows three fixed source links.'])
M['bodies']={
'left':entry('''
...KKKKKKKKKKKKKKKKKK
..KHHHHHHHHHHHHHHHHHHK
.KHHHHHHBBBBBBBBHHHHHHWK
KHHHHHWBNNNNNNNNBHHHHHWK
KHHHHHWNNNNNNNNNNWHHHWWK
KHWWWWWNNNNNNNNNNWWWWWWK
KHWWWWWBNNNNNNNNBWWWWWSK
KWWWWWWWWBBBBBBBWWWWWSSSK
KWWNNNWWWWWWWWWWNNNNNSSK
KWSNNNNWWWWWWWWNNNNNNNSK
.KSNNNNSSSSSSSSNNNNNNSK
..KNNNNSSSSSSSSBNNNNBSK
...KNNBFFFFFFFFFBBBBFK
...KKKKKKKKKKKKKKKKKKK
''',[-12,-7]),
'right':{'mirror':'left','offset':[-11,-7]},
'down':entry('''
....KKKK
..KKHHHHKK
.KHHHHHHHHK
KHHHBBBBHHHK
KHHBNNNNBHHK
KHWNNNNNNWHK
KHWNNNNNNWHK
KHWNNNNNNWHK
KHWBNNNNBWWK
KWWWWBBBWWWK
KWWWWWWWWSSK
KWWWWWWWWSSK
KWWWWWWWWSSK
.KWWWWWWSSK
.KWWWWWWFSK
.KNWWWWNNSK
..KNWWNNSK
..KWWWWSSK
...KKKKKK
''',[-6,-11]),
'up':entry('''
....KKKK
..KKHHHHKK
.KHHHHHHHHK
KHHHHBBBBHHK
KHHWBNNNNBHK
KHHWNNNNNNWK
KHWWNNNNNNWK
KHWWNNNNNNWK
KHWWBNNNNBWK
KWWWWBBBBWWK
KWWWWWWWWSSK
KWWWWWWWWSSK
KWWWWWWWWSSK
KWWWWWWWWSSK
KWWWWWWWWSSK
.KWWWWWWSSK
.KWWWWWWFSK
.KNWWWWNNSK
..KNWWNNSK
..KWWWWSSK
...KKKKKK
''',[-6,-10])}
M['heads']={
'left':entry('''
.......KK
......KQK
......KRK
.....KKWKK
....KHHWWK
...KWWNNNWK
...KWENNNNK
..KWWNNNNNBK
.KRRRNNNNNBK
KQRRRRNNNBK
KQRERRRRBK
.KQQRRQQK
..KKKKKK
''',[-7,-7]),
'right':entry('''
....KK
....KQK
....KRK
...KKWKK
..KHHHWWK
.KWWHBBBWK
.KWWHWWWEK
KWWWWWWWWK
KWWWWWRRRRK
.KWWWRRRRRQK
..KWWRRRERQK
...KQQRRQQK
....KKKKKK
''',[-5,-7]),
'down':entry('''
.....KKKKK
....KHHWWWK
KKK.KHHWWNK.KKK
KQRKKWWWWNNKKRQK
.KKKWWWWWNNNKKK
....KWWEWNNK
....KWWWNENK
....KWWWWNNK
....KRRRRRRK
...KRRRRRRRQK
...KQERRRREQK
....KQRRRRQK
.....KKKKKK
''',[-8,-5]),
'up':entry('''
.....KKKKK
....KHHWWNK
KKKKKHHWWNNKKKKK
KNBNKWWWNNNKBNNK
.KKKKWWWNNNKKKK
....KWWWNNNK
....KWWWNNSK
.....KWWSSK
......KKKK
''',[-8,-4])}
M['hooves']={
'near':entry('''
FFF
NEK
''',[-1,0]),
'far':entry('''
SSS
KNK
''',[-1,0]),
'rear':entry('''
FNF
KKK
''',[-1,0])}
M['udders']={'left':entry('''
..RRR
.RRRRQ
RRRRQQQ
.RRQQQ
..Q.Q
''',[-3,-1]),'right':{'mirror':'left','offset':[-3,-1]},'up':entry('''
.RRRR
RRRRQQ
.RRQQ
..Q.Q
''',[-3,0]),'down':entry('''
.RRRR
RRRRQQ
..Q.Q
''',[-3,0])}
(S/'masters.json').write_text(json.dumps(M,indent=2)+'\n',encoding='utf8');print('COW_MASTERS_WRITTEN')
