"""Own domestic pig palette-letter masters, derived from independent pig guides."""
from pathlib import Path
import json
S=Path(__file__).resolve().parent
def entry(text,offset):
 rows=text.strip('\n').splitlines();w=max(map(len,rows));return dict(pixels=[r.ljust(w,'.') for r in rows],offset=offset)
M=dict(identity='piglet-draft-v1-drawing-02',species='pale domestic pig with undocked curl tail',palette={'K':'#514943','H':'#ead0b6','B':'#dab39d','R':'#bb8e83','S':'#927266','N':'#8b5557','W':'#f0dbc0','F':'#6f7762','E':'#25322f','Q':'#c77f78'},stylization=['Stocky own pig barrel, low neck, long snout and broad nose disc; not a livestock recolor.','Pale pink upper plane, warm flank and restrained rose belly; no spots or invented fur.','Full fixed head/snout/eye template during walking; rear hides front eyes/nostrils.','Broad ear triangles follow rigid independently projected volumes; simplified pixel tip/hull changes are intentional.','Curly mesh tail is drawn as a tiny open curl following actual projected centerline, with no per-frame geometry scaling.'])
M['bodies']={
'left':entry('''
.............KKKK
...KKKKKKKKKKHHHHKK
..KHHHHHHHHHHHHHHHHK
.KHHHHHHHHHHHHHHHHHHK
KHHHHHHHHHHHHHHHHHBBK
KBBBBBBBBBBBBBBBBBBBK
KBBBBBBBBBBBBBBBBBBBK
KBBBBBBBBBBBBBBBBBBRK
.KBBBBBBBBBBBBBBRRRK
..KBBBBBBBBBBRRRRRK
...KRRRRRRRRRRRRK
....KKKKKKKKKKKK
''',[-10,-6]),
'right':{'mirror':'left','offset':[-9,-6]},
'down':entry('''
...KKKKKK
..KHHHHHHK
.KHHHHHHHHK
KHHHHHHHHHHK
KHHHHHHHHHBK
KHHHHHHHHBBK
KHHHHHHHBBBK
KBBBBBBBBBBK
KBBBBBBBBBBK
KBBBBBBBBBBK
KBBBBBBBBBRK
.KBBBBBBRRK
.KBBBBBRRRK
..KBBRRRRK
...KRRRRK
....KKKK
''',[-6,-9]),
'up':entry('''
....KKKK
..KKHHHHKK
.KHHHHHHHHK
KHHHHHHHHHHK
KHHHHHHHHHBK
KHHHHHHHHBBK
KHHHHHHHBBBK
KBBBBBBBBBBK
KBBBBBBBBBBK
KBBBBBBBBBBK
KBBBBBBBBBRK
KBBBBBBBBRRK
.KBBBBBRRRK
.KBBBBRRRRK
..KRRRRRRK
...KKKKKK
''',[-6,-7])}
M['heads']={
'left':entry('''
...KKKKK
..KHHHHHK
.KHHHHHHBK
KQBHHEBBBK
KQQBBBBBBK
KEQBBBBBRK
.KQQBRRRK
..KKKKKK
''',[-6,-3]),
'right':{'mirror':'left','offset':[-4,-3]},
'down':entry('''
..KKKKK
.KHHHHHK
KHHHHHHBK
KBEBBEBBK
KBBBBBBBK
.KBBBBBK
.KQQQQQK
.KQEQEQK
.KQQQQQK
..KKKKK
''',[-4,-3]),
'up':entry('''
..KKKKK
.KHHHHHK
KHHHHHHBK
KHHHHHBBK
KBBBBBBBK
.KBBBBBK
..KRRRK
...KKK
''',[-4,-4])}
M['hooves']={
'near':entry('''
KK
EN
''',[-1,-1]),
'far':entry('''
KK
FE
''',[-1,-1]),
'rear':entry('''
KK
EE
''',[-1,-1])}
(S/'masters.json').write_text(json.dumps(M,indent=2)+'\n',encoding='utf8');print(M['identity'])
