import type { CVarDesc } from "./CVar.js";

/** Shared server CVar definitions — used by both server (for real registration) and client (for stubs). */
export const SERVER_CVAR_DEFS: readonly CVarDesc[] = [
  {
    name: "sv_tickrate",
    description: "Server command tick rate (Hz, legacy alias for sv_tick_ms)",
    type: "number",
    defaultValue: 60,
    min: 10,
    max: 240,
    category: "sv",
  },
  {
    name: "sv_tick_ms",
    description: "Server command tick interval in milliseconds (capped at 100ms)",
    type: "number",
    defaultValue: 1000 / 60,
    min: 1,
    max: 100,
    category: "sv",
  },
  {
    name: "sv_physics_mult",
    description: "Physics substeps per command tick (1 = same as command tick)",
    type: "number",
    defaultValue: 1,
    min: 1,
    max: 16,
    category: "sv",
  },
  {
    name: "sv_speed",
    description: "Player speed multiplier",
    type: "number",
    defaultValue: 1,
    min: 0.1,
    max: 20,
    category: "sv",
  },
  {
    name: "sv_gravity",
    description: "Gravity multiplier (1 = normal, 0.5 = moon, 2 = heavy)",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 20,
    category: "sv",
  },
  {
    name: "sv_timescale",
    description: "Server time scale (1 = normal, 0.5 = half speed, 2 = double)",
    type: "number",
    defaultValue: 1,
    min: 0.1,
    max: 10,
    category: "sv",
  },
  {
    name: "sv_smalljumps",
    description:
      "Allow variable-height jumps (tap = small, hold = full). Off = always full height.",
    type: "boolean",
    defaultValue: false,
    category: "sv",
  },
  {
    name: "sv_nobunnyhop",
    description: "Clamp player speed to wishspeed on jump (disables bunny-hopping)",
    type: "boolean",
    defaultValue: false,
    category: "sv",
  },
  {
    name: "sv_friction",
    description: "Ground friction (QW: 4, ≥60 = instant stop)",
    type: "number",
    defaultValue: 100,
    min: 0,
    max: 1000,
    category: "sv",
  },
  {
    name: "sv_accelerate",
    description: "Ground acceleration (QW: 10, ≥60 = instant)",
    type: "number",
    defaultValue: 100,
    min: 0,
    max: 1000,
    category: "sv",
  },
  {
    name: "sv_airaccelerate",
    description: "Air acceleration (QW: 0.7 — lower = less air control)",
    type: "number",
    defaultValue: 1,
    min: 0,
    max: 1000,
    category: "sv",
  },
  {
    name: "sv_airwishcap",
    description: "Air wishspeed cap — limits per-frame speed gain from strafing (QW: 30)",
    type: "number",
    defaultValue: 6,
    min: 0,
    max: 1000,
    category: "sv",
  },
  {
    name: "sv_platformerair",
    description:
      "Platformer-style air control (ground friction+accel apply mid-air). Off = QW air physics.",
    type: "boolean",
    defaultValue: true,
    category: "sv",
  },
  {
    name: "sv_stopspeed",
    description: "Friction control floor speed (QW: 100, default: 16)",
    type: "number",
    defaultValue: 16,
    min: 0,
    max: 500,
    category: "sv",
  },
];
